services:
  - type: web
    name: baseDR-seeding
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/seed_all.js
    envVars:
      - key: SEED_N
        value: 200000
      - key: SEED_BATCH
        value: 10000
      - key: SEED_WORKERS
        value: 4
      - key: MONGO_URI
        sync: false
